In [10]:
# Connecting to an API/Pulling in the data and cleaning/formatting
import quandl
import json
import os
import datetime as dt

In [6]:
# Open the quandlAPI.json file
with open('quandlAPI.json') as f:
    keys = json.load(f)
    quandlapi = keys['api_key']

quandl.ApiConfig.api_key = quandlapi

In [8]:
data_aapl = quandl.get('WIKI/AAPL', paginate = True)

In [9]:
data_aapl.head(5)

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
1980-12-12,28.75,28.87,28.75,28.75,2093900.0,0.0,1.0,0.422706,0.424470,0.422706,0.422706,117258400.0
1980-12-15,27.38,27.38,27.25,27.25,785200.0,0.0,1.0,0.402563,0.402563,0.400652,0.400652,43971200.0
1980-12-16,25.37,25.37,25.25,25.25,472000.0,0.0,1.0,0.373010,0.373010,0.371246,0.371246,26432000.0
1980-12-17,25.87,26.00,25.87,25.87,385900.0,0.0,1.0,0.380362,0.382273,0.380362,0.380362,21610400.0
1980-12-18,26.63,26.75,26.63,26.63,327900.0,0.0,1.0,0.391536,0.393300,0.391536,0.391536,18362400.0

In [43]:
start = dt.date(2018,1,31)
end = dt.date(2018,12,31)
# data = quandl.get("FRED/GDP", start_date="2001-12-31", end_date="2005-12-31")
# data_aapl_tsp = quandl.get("WIKI/AAPL", rows=10)
data_aapl_tsp = quandl.get("WIKI/AAPL", start_date=start, end_date=end)

In [44]:
data_aapl_tsp

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
2018-01-31,166.870,168.4417,166.5000,167.430,30984099.0,0.0,1.0,166.870,168.4417,166.5000,167.430,30984099.0
2018-02-01,167.165,168.6200,166.7600,167.780,38099665.0,0.0,1.0,167.165,168.6200,166.7600,167.780,38099665.0
2018-02-02,166.000,166.8000,160.1000,160.370,85436075.0,0.0,1.0,166.000,166.8000,160.1000,160.370,85436075.0
2018-02-05,159.100,163.8800,156.0000,157.490,66090446.0,0.0,1.0,159.100,163.8800,156.0000,157.490,66090446.0
2018-02-06,154.830,163.7200,154.0000,163.030,66625484.0,0.0,1.0,154.830,163.7200,154.0000,163.030,66625484.0
2018-02-07,163.085,163.4000,159.0685,159.540,50852130.0,0.0,1.0,163.085,163.4000,159.0685,159.540,50852130.0
2018-02-08,160.290,161.0000,155.0300,155.320,49594129.0,0.0,1.0,160.290,161.0000,155.0300,155.320,49594129.0
2018-02-09,157.070,157.8900,150.2400,155.970,66723743.0,0.0,1.0,157.070,157.8900,150.2400,155.970,66723743.0
2018-02-12,158.500,163.8900,157.5100,162.710,60560145.0,0.0,1.0,158.500,163.8900,157.5100,162.710,60560145.0
2018-02-13,161.950,164.7500,161.6500,164.340,32104756.0,0.0,1.0,161.950,164.7500,161.6500,164.340,32104756.0
2018-02-14,163.045,167.5400,162.8800,167.370,39669178.0,0.0,1.0,163.045,167.5400,162.8800,167.370,39669178.0
2018-02-15,169.790,173.0900,169.0000,172.990,50609595.0,0.0,1.0,169.790,173.0900,169.0000,172.990,50609595.0
2018-02-16,172.360,174.8200,171.7700,172.430,39638793.0,0.0,1.0,172.360,174.8200,171.7700,172.430,39638793.0
2018-02-20,172.050,174.2600,171.4200,171.850,33531012.0,0.0,1.0,172.050,174.2600,171.4200,171.850,33531012.0
2018-02-21,172.830,174.1200,171.0100,171.070,35833514.0,0.0,1.0,172.830,174.1200,171.0100,171.070,35833514.0
2018-02-22,171.800,173.9500,171.7100,172.600,30504116.0,0.0,1.0,171.800,173.9500,171.7100,172.600,30504116.0
2018-02-23,173.670,175.6500,173.5400,175.555,33329232.0,0.0,1.0,173.670,175.6500,173.5400,175.555,33329232.0
2018-02-26,176.350,179.3900,176.2100,178.970,36886432.0,0.0,1.0,176.350,179.3900,176.2100,178.970,36886432.0
2018-02-27,179.100,180.4800,178.1600,178.390,38685165.0,0.0,1.0,179.100,180.4800,178.1600,178.390,38685165.0
2018-02-28,179.260,180.6150,178.0500,178.120,33604574.0,0.0,1.0,179.260,180.6150,178.0500,178.120,33604574.0
2018-03-01,178.540,179.7750,172.6600,175.000,48801970.0,0.0,1.0,178.540,179.7750,172.6600,175.000,48801970.0
2018-03-02,172.800,176.3000,172.4500,176.210,38453950.0,0.0,1.0,172.800,176.3000,172.4500,176.210,38453950.0
2018-03-05,175.210,177.7400,174.5200,176.820,28401366.0,0.0,1.0,175.210,177.7400,174.5200,176.820,28401366.0
2018-03-06,177.910,178.2500,176.1300,176.670,23788506.0,0.0,1.0,177.910,178.2500,176.1300,176.670,23788506.0
2018-03-07,174.940,175.8500,174.2700,175.030,31703462.0,0.0,1.0,174.940,175.8500,174.2700,175.030,31703462.0
2018-03-08,175.480,177.1200,175.0700,176.940,23163767.0,0.0,1.0,175.480,177.1200,175.0700,176.940,23163767.0
2018-03-09,177.960,180.0000,177.3900,179.980,31385134.0,0.0,1.0,177.960,180.0000,177.3900,179.980,31385134.0
2018-03-12,180.290,182.3900,180.2100,181.720,32055405.0,0.0,1.0,180.290,182.3900,180.2100,181.720,32055405.0
2018-03-13,182.590,183.5000,179.2400,179.970,31168404.0,0.0,1.0,182.590,183.5000,179.2400,179.970,31168404.0
2018-03-14,180.320,180.5200,177.8100,178.440,29075469.0,0.0,1.0,180.320,180.5200,177.8100,178.440,29075469.0
2018-03-15,178.500,180.2400,178.0701,178.650,22584565.0,0.0,1.0,178.500,180.2400,178.0701,178.650,22584565.0
2018-03-16,178.650,179.1200,177.6200,178.020,36836456.0,0.0,1.0,178.650,179.1200,177.6200,178.020,36836456.0
2018-03-19,177.320,177.4700,173.6600,175.300,32804695.0,0.0,1.0,177.320,177.4700,173.6600,175.300,32804695.0
2018-03-20,175.240,176.8000,174.9400,175.240,19314039.0,0.0,1.0,175.240,176.8000,174.9400,175.240,19314039.0
2018-03-21,175.040,175.0900,171.2600,171.270,35247358.0,0.0,1.0,175.040,175.0900,171.2600,171.270,35247358.0
2018-03-22,170.000,172.6800,168.6000,168.845,41051076.0,0.0,1.0,170.000,172.6800,168.6000,168.845,41051076.0
2018-03-23,168.390,169.9200,164.9400,164.940,40248954.0,0.0,1.0,168.390,169.9200,164.9400,164.940,40248954.0
2018-03-26,168.070,173.1000,166.4400,172.770,36272617.0,0.0,1.0,168.070,173.1000,166.4400,172.770,36272617.0
2018-03-27,173.680,175.1500,166.9200,168.340,38962839.0,0.0,1.0,173.680,175.1500,166.9200,168.340,38962839.0

In [22]:
start = dt.date(2020,10,1)
start.isoformat()

'2020-10-01'